# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
