# Generated by Django 5.1.2 on 2025-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_explanation_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
