# Generated by Django 5.1.2 on 2026-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_question_ai_cost_question_ai_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField()),
                ("total_quizzes", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("total_submissions", models.IntegerField()),
                ("submissions_today", models.IntegerField()),
                (
                    "avg_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={},
        ),
    ]
