# Generated by Django 5.1.2 on 2026-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_admindailymetric_alter_quiz_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admindailymetric",
            options={
                "verbose_name": "Admin Daily Metric",
                "verbose_name_plural": "Admin Daily Metrics",
            },
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_file",
            field=models.FileField(blank=True, null=True, upload_to="quiz/"),
        ),
    ]
