# Generated by Django 5.1.2 on 2026-02-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_quizattempt_and_answers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplanationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="attemptanswer",
            new_name="quiz_attemp_attempt_04e8c2_idx",
            old_name="quiz_attempt_attempt_1a1f68_idx",
        ),
        migrations.RenameIndex(
            model_name="quizattempt",
            new_name="quiz_quizat_user_id_47c6be_idx",
            old_name="quiz_quizat_user_id_4a6a8c_idx",
        ),
        migrations.RenameIndex(
            model_name="quizattempt",
            new_name="quiz_quizat_user_id_2f0af4_idx",
            old_name="quiz_quizat_user_id_7c5128_idx",
        ),
        migrations.RenameIndex(
            model_name="quizattempt",
            new_name="quiz_quizat_submitt_5a5842_idx",
            old_name="quiz_quizat_submitt_b6ff0e_idx",
        ),
        migrations.AddField(
            model_name="explanationtask",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanation_tasks",
                to="quiz.question",
            ),
        ),
        migrations.AddField(
            model_name="explanationtask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
