# Generated by Django 5.1.2 on 2024-11-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creatde_at',
            new_name='created_at',
        ),
    ]
